{% set name = "datalad-container" %}
{% set pypiname = "datalad_container" %}
{% set version = "1.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypiname[0] }}/{{ pypiname }}/{{ pypiname }}-{{ version }}.tar.gz
  sha256: 771295e5b2cd038a3f8b84564d8ae5afc2398be846222c4df7bb6da393b6b7c0

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.2
    - pip
    - setuptools
    - pypandoc
  run:
    - python >=3.2
    - datalad >=0.11.5
    - requests >=1.2

test:
  requires:
    - nose >=1.3.4

  imports:
    - datalad_container

about:
  home: http://github.com/datalad/datalad-container
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: DataLad extension package for working with containerized environments
  doc_url: http://docs.datalad.org/projects/container/en/latest/index.html
  dev_url: https://github.com/datalad/datalad-container/

extra:
  recipe-maintainers:
    - yarikoptic
