{% set name = "datalad-container" %}
{% set pypiname = "datalad_container" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypiname[0] }}/{{ pypiname }}/{{ pypiname }}-{{ version }}.tar.gz
  sha256: 6eb9878283e7fd50201349ad2252ff579a13781ac5bfd27d823aec6d15041fba

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.2
    - pip
    - setuptools
    - pypandoc
  run:
    - python >=3.2
    - datalad >=0.11.5
    - requests >=1.2

test:
  requires:
    - nose >=1.3.4

  imports:
    - datalad_container

about:
  home: http://github.com/datalad/datalad-container
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: DataLad extension package for working with containerized environments
  doc_url: http://docs.datalad.org/projects/container/en/latest/index.html
  dev_url: https://github.com/datalad/datalad-container/

extra:
  recipe-maintainers:
    - yarikoptic
