travis:
  secure:
    BINSTAR_TOKEN: Ds9nqFdxHaOl/xlzm7gyH5MqwxyuGUQ+8iW/hPHHj/NqCSgocGjvl8i38Irg2QTOdI9wE8Id8/tdeqqC1LR9DctmY4pbW9V1esUae+mfackqe5Ei/Cki4YbRx5tLVmAfP98JzdTlRuAWi9fUhaGNptWJ8ju4yq7GHKHeJAWg/QK2BhcX1rUfSG2bKb1LHJE4V1WEwoR4L7pM0wxBHlc4l1KgI477blUl3+NYP9U1x2UsYvsAjC9jI9hzVmDVMq/R9nNaWKw/rXz1Sk+/pai93yZOn7P5lN+jGV+WiiCdp+UtQ7ArQUD6AZpoRj8dnv17/HU8tlTrvqKPMbvbpYz5MytdBKkS+n3Yjq/pF7V0LSZ+NjHgb2kHV8XcKgn1USk5zjalgcQiIn+3DKdLz0V82B5Q7YszgGl4ueW7RlMxH2TfGI4WO6KJUgX+HRBDjTb1/JNo3Db77t8ebJ1Ggyt6bR/Rsoe6GVdaqh6IJUElsFiuTh9EbzEB7XUpFx7ANRanTJ2kNBYYkbeTCiq0WIeLai68eRu2RtYBMvW0HJa8+y1sFyYJ5tgtO1zXrWPV5SBOQ3dNtGfUs2IleLxnqoVktRhDG3VLq1RbrxDbeYeaRZufZOoqPyKMvbdO33SzA+DRKUUbnUEn6YWjMl8HcfsrmtccccQa/OKpWH3Bsn8DbMA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
